// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Role         string
	KycStatus    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	KycFlags     pqtype.NullRawMessage
}
