// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restaurant_profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRestaurantProfile = `-- name: CreateRestaurantProfile :one
INSERT INTO restaurant_profiles (
    user_id,
    display_name,
    tagline,
    location,
    seats,
    cuisine_types,
    mentorship_style,
    description,
    culture_keywords,
    benefits,
    support_programs,
    learning_highlights
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, name, display_name, tagline, location, seats, cuisine_types,
    mentorship_style, description, culture_keywords, benefits, support_programs,
    learning_highlights, address, created_at, updated_at
`

type CreateRestaurantProfileParams struct {
	UserID             pgtype.UUID
	DisplayName        pgtype.Text
	Tagline            pgtype.Text
	Location           pgtype.Text
	Seats              pgtype.Int4
	CuisineTypes       []string
	MentorshipStyle    pgtype.Text
	Description        pgtype.Text
	CultureKeywords    []string
	Benefits           []string
	SupportPrograms    []string
	LearningHighlights []byte
}

type CreateRestaurantProfileRow struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Name               string
	DisplayName        pgtype.Text
	Tagline            pgtype.Text
	Location           pgtype.Text
	Seats              pgtype.Int4
	CuisineTypes       []string
	MentorshipStyle    pgtype.Text
	Description        pgtype.Text
	CultureKeywords    []string
	Benefits           []string
	SupportPrograms    []string
	LearningHighlights []byte
	Address            pgtype.Text
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

func (q *Queries) CreateRestaurantProfile(ctx context.Context, arg CreateRestaurantProfileParams) (CreateRestaurantProfileRow, error) {
	row := q.db.QueryRow(ctx, createRestaurantProfile,
		arg.UserID,
		arg.DisplayName,
		arg.Tagline,
		arg.Location,
		arg.Seats,
		arg.CuisineTypes,
		arg.MentorshipStyle,
		arg.Description,
		arg.CultureKeywords,
		arg.Benefits,
		arg.SupportPrograms,
		arg.LearningHighlights,
	)
	var i CreateRestaurantProfileRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayName,
		&i.Tagline,
		&i.Location,
		&i.Seats,
		&i.CuisineTypes,
		&i.MentorshipStyle,
		&i.Description,
		&i.CultureKeywords,
		&i.Benefits,
		&i.SupportPrograms,
		&i.LearningHighlights,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRestaurantProfile = `-- name: DeleteRestaurantProfile :exec
DELETE FROM restaurant_profiles
WHERE id = $1
`

func (q *Queries) DeleteRestaurantProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRestaurantProfile, id)
	return err
}

const getRestaurantProfileByID = `-- name: GetRestaurantProfileByID :one
SELECT id, user_id, name, display_name, tagline, location, seats, cuisine_types,
    mentorship_style, description, culture_keywords, benefits, support_programs,
    learning_highlights, address, created_at, updated_at
FROM restaurant_profiles
WHERE id = $1
`

type GetRestaurantProfileByIDRow struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Name               string
	DisplayName        pgtype.Text
	Tagline            pgtype.Text
	Location           pgtype.Text
	Seats              pgtype.Int4
	CuisineTypes       []string
	MentorshipStyle    pgtype.Text
	Description        pgtype.Text
	CultureKeywords    []string
	Benefits           []string
	SupportPrograms    []string
	LearningHighlights []byte
	Address            pgtype.Text
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

func (q *Queries) GetRestaurantProfileByID(ctx context.Context, id pgtype.UUID) (GetRestaurantProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getRestaurantProfileByID, id)
	var i GetRestaurantProfileByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayName,
		&i.Tagline,
		&i.Location,
		&i.Seats,
		&i.CuisineTypes,
		&i.MentorshipStyle,
		&i.Description,
		&i.CultureKeywords,
		&i.Benefits,
		&i.SupportPrograms,
		&i.LearningHighlights,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRestaurantProfileByUserID = `-- name: GetRestaurantProfileByUserID :one
SELECT id, user_id, name, display_name, tagline, location, seats, cuisine_types,
    mentorship_style, description, culture_keywords, benefits, support_programs,
    learning_highlights, address, created_at, updated_at
FROM restaurant_profiles
WHERE user_id = $1
`

type GetRestaurantProfileByUserIDRow struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Name               string
	DisplayName        pgtype.Text
	Tagline            pgtype.Text
	Location           pgtype.Text
	Seats              pgtype.Int4
	CuisineTypes       []string
	MentorshipStyle    pgtype.Text
	Description        pgtype.Text
	CultureKeywords    []string
	Benefits           []string
	SupportPrograms    []string
	LearningHighlights []byte
	Address            pgtype.Text
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

func (q *Queries) GetRestaurantProfileByUserID(ctx context.Context, userID pgtype.UUID) (GetRestaurantProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getRestaurantProfileByUserID, userID)
	var i GetRestaurantProfileByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayName,
		&i.Tagline,
		&i.Location,
		&i.Seats,
		&i.CuisineTypes,
		&i.MentorshipStyle,
		&i.Description,
		&i.CultureKeywords,
		&i.Benefits,
		&i.SupportPrograms,
		&i.LearningHighlights,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchRestaurantProfiles = `-- name: SearchRestaurantProfiles :many
SELECT id, user_id, name, display_name, tagline, location, seats, cuisine_types,
    mentorship_style, description, culture_keywords, benefits, support_programs,
    learning_highlights, address, created_at, updated_at
FROM restaurant_profiles
WHERE
    ($1::TEXT IS NULL OR name ILIKE '%' || $1 || '%')
    AND ($2::TEXT[] IS NULL OR cuisine_types && $2::TEXT[])
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchRestaurantProfilesParams struct {
	Column1 string
	Column2 []string
	Limit   int32
	Offset  int32
}

type SearchRestaurantProfilesRow struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Name               string
	DisplayName        pgtype.Text
	Tagline            pgtype.Text
	Location           pgtype.Text
	Seats              pgtype.Int4
	CuisineTypes       []string
	MentorshipStyle    pgtype.Text
	Description        pgtype.Text
	CultureKeywords    []string
	Benefits           []string
	SupportPrograms    []string
	LearningHighlights []byte
	Address            pgtype.Text
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

func (q *Queries) SearchRestaurantProfiles(ctx context.Context, arg SearchRestaurantProfilesParams) ([]SearchRestaurantProfilesRow, error) {
	rows, err := q.db.Query(ctx, searchRestaurantProfiles,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRestaurantProfilesRow
	for rows.Next() {
		var i SearchRestaurantProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DisplayName,
			&i.Tagline,
			&i.Location,
			&i.Seats,
			&i.CuisineTypes,
			&i.MentorshipStyle,
			&i.Description,
			&i.CultureKeywords,
			&i.Benefits,
			&i.SupportPrograms,
			&i.LearningHighlights,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRestaurantProfile = `-- name: UpdateRestaurantProfile :one
UPDATE restaurant_profiles
SET
    display_name = COALESCE($2, display_name),
    tagline = COALESCE($3, tagline),
    location = COALESCE($4, location),
    seats = COALESCE($5, seats),
    cuisine_types = COALESCE($6, cuisine_types),
    mentorship_style = COALESCE($7, mentorship_style),
    description = COALESCE($8, description),
    culture_keywords = COALESCE($9, culture_keywords),
    benefits = COALESCE($10, benefits),
    support_programs = COALESCE($11, support_programs),
    learning_highlights = COALESCE($12, learning_highlights),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, display_name, tagline, location, seats, cuisine_types,
    mentorship_style, description, culture_keywords, benefits, support_programs,
    learning_highlights, address, created_at, updated_at
`

type UpdateRestaurantProfileParams struct {
	ID                 pgtype.UUID
	DisplayName        pgtype.Text
	Tagline            pgtype.Text
	Location           pgtype.Text
	Seats              pgtype.Int4
	CuisineTypes       []string
	MentorshipStyle    pgtype.Text
	Description        pgtype.Text
	CultureKeywords    []string
	Benefits           []string
	SupportPrograms    []string
	LearningHighlights []byte
}

type UpdateRestaurantProfileRow struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Name               string
	DisplayName        pgtype.Text
	Tagline            pgtype.Text
	Location           pgtype.Text
	Seats              pgtype.Int4
	CuisineTypes       []string
	MentorshipStyle    pgtype.Text
	Description        pgtype.Text
	CultureKeywords    []string
	Benefits           []string
	SupportPrograms    []string
	LearningHighlights []byte
	Address            pgtype.Text
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

func (q *Queries) UpdateRestaurantProfile(ctx context.Context, arg UpdateRestaurantProfileParams) (UpdateRestaurantProfileRow, error) {
	row := q.db.QueryRow(ctx, updateRestaurantProfile,
		arg.ID,
		arg.DisplayName,
		arg.Tagline,
		arg.Location,
		arg.Seats,
		arg.CuisineTypes,
		arg.MentorshipStyle,
		arg.Description,
		arg.CultureKeywords,
		arg.Benefits,
		arg.SupportPrograms,
		arg.LearningHighlights,
	)
	var i UpdateRestaurantProfileRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayName,
		&i.Tagline,
		&i.Location,
		&i.Seats,
		&i.CuisineTypes,
		&i.MentorshipStyle,
		&i.Description,
		&i.CultureKeywords,
		&i.Benefits,
		&i.SupportPrograms,
		&i.LearningHighlights,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
