// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    role,
    kyc_status
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, email, password_hash, role, kyc_status, created_at, updated_at, kyc_flags
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Role         string
	KycStatus    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.KycStatus,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KycFlags,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, kyc_status, created_at, updated_at, kyc_flags
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KycFlags,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, kyc_status, created_at, updated_at, kyc_flags
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KycFlags,
	)
	return i, err
}

const updateUserKYCStatus = `-- name: UpdateUserKYCStatus :exec
UPDATE users
SET kyc_status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserKYCStatusParams struct {
	ID        uuid.UUID
	KycStatus string
}

func (q *Queries) UpdateUserKYCStatus(ctx context.Context, arg UpdateUserKYCStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserKYCStatus, arg.ID, arg.KycStatus)
	return err
}
